### ISSUE TITLE
Singlestat metric is throwing error

### ISSUE THREAD

**Issue by perfectayush** [prajwalrao/ambari-metrics-grafana#3]
I have imported dashboard from the Grafana 2.6 insalled by ambari on the ambari metrics collector node and imported them in Grafana 3.0.4. All the graphs are showing up without any issues, But all the singlestats are throwing up error like this:
"Invalid dimensions for plot, width  = 452, height = 0"

I am not able to figure out what that means and why the singlestat graph is not showing up.

When I try to edit the singlestat, after switching some value, the graph shows up, but when I go back to the dashboard, it starts throwing error again. Do you have insight into what could be wrong here?

**Comment by prajwalrao** [comment]
@perfectayush - You can solve this in 2 ways.

_Method 1_
You should ideally be importing the dashboards from here - https://github.com/prajwalrao/ambari-metrics-grafana/tree/master/dashboards

_Method 2_
Another way to fix it would be to set the height for each of the single stat graphs.

Edit Single Stat > General > Height > Set it to 100px, and the error should go away.

The second method might be tedious if you have a lot of single stats, which is why importing the JSON from the first method would be better.

Let me know how it goes..

**Comment by perfectayush** [comment]
Thanks for your response. I just figured out myself that the issue resolves after changing the row height. Also thanks for the dashboards link, i missed it.
